// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-06-15 20:07:09.2242231 +0800 CST m=+0.063535401

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Doremy",
            "url": "https://dimdoremy.github.io/"
        },
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/accept_recruit": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recruit-routers"
                ],
                "summary": "接收客户端完成的积分",
                "parameters": [
                    {
                        "description": "招募请求",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routers.requests"
                        }
                    }
                ],
                "responses": {
                    "200": {},
                    "400": {
                        "description": "错误信息",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    }
                }
            }
        },
        "/add_into_recruit": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recruit-routers"
                ],
                "summary": "添加招募进入redis缓存",
                "parameters": [
                    {
                        "description": "招募请求",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routers.requests"
                        }
                    }
                ],
                "responses": {
                    "200": {},
                    "400": {
                        "description": "错误信息",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    }
                }
            }
        },
        "/check_room": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recruit-routers"
                ],
                "summary": "检查房间存在",
                "parameters": [
                    {
                        "description": "招募请求",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routers.requests"
                        }
                    }
                ],
                "responses": {
                    "200": {},
                    "400": {
                        "description": "错误信息",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    }
                }
            }
        },
        "/complete_recruit": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recruit-routers"
                ],
                "summary": "结算请求",
                "parameters": [
                    {
                        "description": "招募请求",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routers.requests"
                        }
                    }
                ],
                "responses": {
                    "200": {},
                    "400": {
                        "description": "错误信息",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    }
                }
            }
        },
        "/delete_room": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recruit-routers"
                ],
                "summary": "从redis缓存销毁招募房间",
                "parameters": [
                    {
                        "description": "招募请求",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routers.requests"
                        }
                    }
                ],
                "responses": {
                    "200": {},
                    "400": {
                        "description": "错误信息",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    }
                }
            }
        },
        "/deletehandbook": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book-routers"
                ],
                "summary": "删除图鉴数据库的指定条目",
                "parameters": [
                    {
                        "description": "删除用户信息",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.HandBook"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    },
                    "400": {
                        "description": "400 bad request",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    }
                }
            }
        },
        "/deleteuserdata": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-routers"
                ],
                "summary": "更新单个用户信息",
                "parameters": [
                    {
                        "description": "更新的用户信息",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    },
                    "400": {
                        "description": "400 bad request",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    }
                }
            }
        },
        "/deleteuserpiece": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "piece-routers"
                ],
                "summary": "删除背包数据库指定条目",
                "parameters": [
                    {
                        "description": "单个用户信息",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserPiece"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "删除成功",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    },
                    "400": {
                        "description": "删除失败",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    }
                }
            }
        },
        "/handbookbyopenid": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book-routers"
                ],
                "summary": "获取单个用户图鉴列表信息",
                "parameters": [
                    {
                        "description": "单个用户信息",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.HandBook"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "单个用户图鉴信息的json数据",
                        "schema": {
                            "$ref": "#/definitions/model.HandBook"
                        }
                    },
                    "400": {
                        "description": "400 bad request",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    }
                }
            }
        },
        "/init_recruit": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recruit-routers"
                ],
                "summary": "公共 活动 招募的读取",
                "parameters": [
                    {
                        "description": "招募请求",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routers.requests"
                        }
                    }
                ],
                "responses": {
                    "200": {},
                    "400": {
                        "description": "错误信息",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    }
                }
            }
        },
        "/inserthandbook": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book-routers"
                ],
                "summary": "注册新用户新建图鉴信息",
                "parameters": [
                    {
                        "description": "注册用户信息",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.HandBook"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注册成功",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    },
                    "400": {
                        "description": "注册失败",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    }
                }
            }
        },
        "/insertuserdata": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-routers"
                ],
                "summary": "注册单个用户",
                "parameters": [
                    {
                        "description": "注册用户信息",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注册成功",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    },
                    "400": {
                        "description": "注册失败",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    }
                }
            }
        },
        "/insertuserpiece": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "piece-routers"
                ],
                "summary": "注册单个用户，新建背包",
                "parameters": [
                    {
                        "description": "单个用户背包信息",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserPiece"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注册成功",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    },
                    "400": {
                        "description": "注册失败",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    }
                }
            }
        },
        "/new_room": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recruit-routers"
                ],
                "summary": "建立招募房间到redis缓存",
                "parameters": [
                    {
                        "description": "招募请求",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routers.requests"
                        }
                    }
                ],
                "responses": {
                    "200": {},
                    "400": {
                        "description": "错误信息",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    }
                }
            }
        },
        "/openid": {
            "post": {
                "description": "用于服务器请求微信服务器进行用户登录授权使用",
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "wechat-router"
                ],
                "summary": "请求微信登录授权",
                "parameters": [
                    {
                        "description": "用户的登录包",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routers.userCode"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "请求结果",
                        "schema": {
                            "$ref": "#/definitions/routers.userCode"
                        }
                    },
                    "400": {
                        "description": "请求没到达",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    }
                }
            }
        },
        "/piecebyopenid": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "piece-routers"
                ],
                "summary": "获取单个用户背包信息",
                "parameters": [
                    {
                        "description": "单个用户信息",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserPiece"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "单个用户信息的json数据",
                        "schema": {
                            "$ref": "#/definitions/model.UserPiece"
                        }
                    }
                }
            }
        },
        "/querybyopenid": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-routers"
                ],
                "summary": "获取单个用户信息",
                "parameters": [
                    {
                        "description": "单个用户信息",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "单个用户信息的json数据",
                        "schema": {
                            "$ref": "#/definitions/model.UserData"
                        }
                    },
                    "400": {
                        "description": "400 bad request",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    }
                }
            }
        },
        "/remove_recruit": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recruit-routers"
                ],
                "summary": "从redis缓存退出招募",
                "parameters": [
                    {
                        "description": "招募请求",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routers.requests"
                        }
                    }
                ],
                "responses": {
                    "200": {},
                    "400": {
                        "description": "错误信息",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    }
                }
            }
        },
        "/return_recruit": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recruit-routers"
                ],
                "summary": "恢复客户端所有的redis缓存",
                "parameters": [
                    {
                        "description": "招募请求",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routers.requests"
                        }
                    }
                ],
                "responses": {
                    "200": {},
                    "400": {
                        "description": "错误信息",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    }
                }
            }
        },
        "/updatehandbook": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book-routers"
                ],
                "summary": "更新单个用户图鉴信息",
                "parameters": [
                    {
                        "description": "更新的用户信息",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.HandBook"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    },
                    "400": {
                        "description": "400 bad request",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    }
                }
            }
        },
        "/updateuserdata": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "user-routers"
                ],
                "summary": "更新单个用户信息",
                "parameters": [
                    {
                        "description": "更新的用户信息",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserData"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    },
                    "400": {
                        "description": "400 bad request",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    }
                }
            }
        },
        "/updateuserpiece": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "piece-routers"
                ],
                "summary": "更新单个用户背包信息",
                "parameters": [
                    {
                        "description": "更新的用户背包信息",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.UserPiece"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "更新成功",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    },
                    "400": {
                        "description": "更新失败",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.HandBook": {
            "type": "object",
            "properties": {
                "monster1": {
                    "type": "integer"
                },
                "monster2": {
                    "type": "integer"
                },
                "monster3": {
                    "type": "integer"
                },
                "monster4": {
                    "type": "integer"
                },
                "monster5": {
                    "type": "integer"
                },
                "monster6": {
                    "type": "integer"
                },
                "monster7": {
                    "type": "integer"
                },
                "openid": {
                    "type": "string"
                }
            }
        },
        "model.MessageBind": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "model.UserData": {
            "type": "object",
            "properties": {
                "avatarurl": {
                    "type": "string"
                },
                "experience": {
                    "type": "integer"
                },
                "lifepoint": {
                    "type": "integer"
                },
                "nickname": {
                    "type": "string"
                },
                "openid": {
                    "type": "string"
                },
                "soul": {
                    "type": "integer"
                },
                "time": {
                    "type": "integer"
                }
            }
        },
        "model.UserPiece": {
            "type": "object",
            "properties": {
                "donghuangzhong": {
                    "type": "integer"
                },
                "fuxiqin": {
                    "type": "integer"
                },
                "haotianta": {
                    "type": "integer"
                },
                "kongtongyin": {
                    "type": "integer"
                },
                "kunlunjing": {
                    "type": "integer"
                },
                "lianyaohu": {
                    "type": "integer"
                },
                "nvwashi": {
                    "type": "integer"
                },
                "openid": {
                    "type": "string"
                },
                "pangufu": {
                    "type": "integer"
                },
                "shennongding": {
                    "type": "integer"
                },
                "xuanyuanjian": {
                    "type": "integer"
                }
            }
        },
        "routers.requests": {
            "type": "object",
            "properties": {
                "describe": {
                    "type": "string"
                },
                "makerid": {
                    "type": "string"
                },
                "openid": {
                    "type": "string"
                },
                "time": {
                    "type": "integer"
                },
                "title": {
                    "type": "string"
                }
            }
        },
        "routers.userCode": {
            "type": "object",
            "properties": {
                "code": {
                    "type": "string"
                },
                "openid": {
                    "type": "string"
                },
                "session_key": {
                    "type": "string"
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0-golang",
	Host:        "127.0.0.1:8848",
	BasePath:    "/api",
	Schemes:     []string{},
	Title:       "知夕后台Api接口",
	Description: "用于知夕番茄钟程序的后台api文档",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
