// GENERATED BY THE COMMAND ABOVE; DO NOT EDIT
// This file was generated by swaggo/swag at
// 2020-05-15 16:08:28.0142024 +0800 CST m=+0.052942501

package docs

import (
	"bytes"
	"encoding/json"
	"strings"

	"github.com/alecthomas/template"
	"github.com/swaggo/swag"
)

var doc = `{
    "schemes": {{ marshal .Schemes }},
    "swagger": "2.0",
    "info": {
        "description": "{{.Description}}",
        "title": "{{.Title}}",
        "contact": {
            "name": "Doremy",
            "url": "https://dimdoremy.github.io/"
        },
        "license": {},
        "version": "{{.Version}}"
    },
    "host": "{{.Host}}",
    "basePath": "{{.BasePath}}",
    "paths": {
        "/allhandbook": {
            "get": {
                "description": "用于测试的Api，请不要在正式开发中使用",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book-routers"
                ],
                "summary": "获取全部用户图鉴列表",
                "responses": {
                    "200": {
                        "description": "获取到的全部数据库条目",
                        "schema": {
                            "$ref": "#/definitions/model.HandBook"
                        }
                    },
                    "404": {
                        "description": "404 not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/allrecruit": {
            "get": {
                "description": "用于测试的Api，请不要在正式开发中使用",
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recruit-routers"
                ],
                "summary": "获取全部用户图鉴列表",
                "responses": {
                    "200": {
                        "description": "获取到的全部数据库条目",
                        "schema": {
                            "$ref": "#/definitions/routers.recruits"
                        }
                    },
                    "404": {
                        "description": "404 not found",
                        "schema": {
                            "type": "string"
                        }
                    }
                }
            }
        },
        "/deletehandbook": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book-routers"
                ],
                "summary": "删除图鉴数据库的指定条目",
                "parameters": [
                    {
                        "description": "删除用户信息",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.HandBook"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "单个用户信息的背包json数据",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    },
                    "400": {
                        "description": "400 bad request",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    }
                }
            }
        },
        "/handbookbyopenid": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book-routers"
                ],
                "summary": "获取单个用户图鉴列表信息",
                "parameters": [
                    {
                        "description": "单个用户信息",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.HandBook"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "单个用户信息的背包json数据",
                        "schema": {
                            "$ref": "#/definitions/model.HandBook"
                        }
                    },
                    "400": {
                        "description": "400 bad request",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    }
                }
            }
        },
        "/inserthandbook": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book-routers"
                ],
                "summary": "注册新用户新建图鉴信息",
                "parameters": [
                    {
                        "description": "注册用户信息",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.HandBook"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注册成功",
                        "schema": {
                            "$ref": "#/definitions/model.HandBook"
                        }
                    },
                    "400": {
                        "description": "注册失败",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    }
                }
            }
        },
        "/insertrecruit": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recruit-routers"
                ],
                "summary": "注册新招募板信息",
                "parameters": [
                    {
                        "description": "注册新招募板信息",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routers.recruitJSON"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "注册成功",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    },
                    "400": {
                        "description": "注册失败",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    }
                }
            }
        },
        "/recruitbymakerid": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "recruit-routers"
                ],
                "summary": "获取单个用户图鉴列表信息",
                "parameters": [
                    {
                        "description": "单个用户信息",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/routers.recruitJSON"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "单个用户信息的背包json数据",
                        "schema": {
                            "$ref": "#/definitions/routers.recruitJSON"
                        }
                    },
                    "400": {
                        "description": "400 bad request",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    }
                }
            }
        },
        "/updatehandbook": {
            "post": {
                "consumes": [
                    "application/json"
                ],
                "produces": [
                    "application/json"
                ],
                "tags": [
                    "book-routers"
                ],
                "summary": "更新单个用户图鉴信息",
                "parameters": [
                    {
                        "description": "更新用户信息",
                        "name": "handBook",
                        "in": "body",
                        "required": true,
                        "schema": {
                            "$ref": "#/definitions/model.HandBook"
                        }
                    }
                ],
                "responses": {
                    "200": {
                        "description": "单个用户信息的背包json数据",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    },
                    "400": {
                        "description": "400 bad request",
                        "schema": {
                            "$ref": "#/definitions/model.MessageBind"
                        }
                    }
                }
            }
        }
    },
    "definitions": {
        "model.HandBook": {
            "type": "object",
            "properties": {
                "monster1": {
                    "type": "integer"
                },
                "monster2": {
                    "type": "integer"
                },
                "monster3": {
                    "type": "integer"
                },
                "monster4": {
                    "type": "integer"
                },
                "monster5": {
                    "type": "integer"
                },
                "monster6": {
                    "type": "integer"
                },
                "monster7": {
                    "type": "integer"
                },
                "openid": {
                    "type": "string"
                }
            }
        },
        "model.MessageBind": {
            "type": "object",
            "properties": {
                "message": {
                    "type": "string"
                }
            }
        },
        "model.RecruitBlock": {
            "type": "object",
            "properties": {
                "bossid": {
                    "type": "integer"
                },
                "bosslife": {
                    "type": "integer"
                },
                "makerid": {
                    "type": "string"
                }
            }
        },
        "model.RecruitList": {
            "type": "object",
            "properties": {
                "gamer1": {
                    "type": "string"
                },
                "gamer2": {
                    "type": "string"
                },
                "gamer3": {
                    "type": "string"
                },
                "makerid": {
                    "type": "string"
                }
            }
        },
        "routers.recruitJSON": {
            "type": "object",
            "properties": {
                "bossid": {
                    "type": "integer"
                },
                "bosslife": {
                    "type": "integer"
                },
                "gamer1": {
                    "type": "string"
                },
                "gamer2": {
                    "type": "string"
                },
                "gamer3": {
                    "type": "string"
                },
                "makerid": {
                    "type": "string"
                }
            }
        },
        "routers.recruits": {
            "type": "object",
            "properties": {
                "blocks": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.RecruitBlock"
                    }
                },
                "lists": {
                    "type": "array",
                    "items": {
                        "$ref": "#/definitions/model.RecruitList"
                    }
                }
            }
        }
    }
}`

type swaggerInfo struct {
	Version     string
	Host        string
	BasePath    string
	Schemes     []string
	Title       string
	Description string
}

// SwaggerInfo holds exported Swagger Info so clients can modify it
var SwaggerInfo = swaggerInfo{
	Version:     "1.0-golang",
	Host:        "127.0.0.1:8848",
	BasePath:    "/api",
	Schemes:     []string{},
	Title:       "知夕后台Api接口",
	Description: "用于知夕番茄钟程序的后台api文档",
}

type s struct{}

func (s *s) ReadDoc() string {
	sInfo := SwaggerInfo
	sInfo.Description = strings.Replace(sInfo.Description, "\n", "\\n", -1)

	t, err := template.New("swagger_info").Funcs(template.FuncMap{
		"marshal": func(v interface{}) string {
			a, _ := json.Marshal(v)
			return string(a)
		},
	}).Parse(doc)
	if err != nil {
		return doc
	}

	var tpl bytes.Buffer
	if err := t.Execute(&tpl, sInfo); err != nil {
		return doc
	}

	return tpl.String()
}

func init() {
	swag.Register(swag.Name, &s{})
}
