basePath: /api
definitions:
  model.HandBook:
    properties:
      monster1:
        type: integer
      monster2:
        type: integer
      monster3:
        type: integer
      monster4:
        type: integer
      monster5:
        type: integer
      monster6:
        type: integer
      monster7:
        type: integer
      openid:
        type: string
    type: object
  model.MessageBind:
    properties:
      message:
        type: string
    type: object
  model.RecruitBlock:
    properties:
      bossid:
        type: integer
      bosslife:
        type: integer
      makerid:
        type: string
    type: object
  model.RecruitList:
    properties:
      gamer1:
        type: string
      gamer2:
        type: string
      gamer3:
        type: string
      makerid:
        type: string
    type: object
  routers.recruitJSON:
    properties:
      bossid:
        type: integer
      bosslife:
        type: integer
      gamer1:
        type: string
      gamer2:
        type: string
      gamer3:
        type: string
      makerid:
        type: string
    type: object
  routers.recruits:
    properties:
      blocks:
        items:
          $ref: '#/definitions/model.RecruitBlock'
        type: array
      lists:
        items:
          $ref: '#/definitions/model.RecruitList'
        type: array
    type: object
host: 127.0.0.1:8848
info:
  contact:
    name: Doremy
    url: https://dimdoremy.github.io/
  description: 用于知夕番茄钟程序的后台api文档
  license: {}
  title: 知夕后台Api接口
  version: 1.0-golang
paths:
  /allhandbook:
    get:
      description: 用于测试的Api，请不要在正式开发中使用
      produces:
      - application/json
      responses:
        "200":
          description: 获取到的全部数据库条目
          schema:
            $ref: '#/definitions/model.HandBook'
        "404":
          description: 404 not found
          schema:
            type: string
      summary: 获取全部用户图鉴列表
      tags:
      - book-routers
  /allrecruit:
    get:
      description: 用于测试的Api，请不要在正式开发中使用
      produces:
      - application/json
      responses:
        "200":
          description: 获取到的全部数据库条目
          schema:
            $ref: '#/definitions/routers.recruits'
        "404":
          description: 404 not found
          schema:
            type: string
      summary: 获取全部用户图鉴列表
      tags:
      - recruit-routers
  /deletehandbook:
    post:
      consumes:
      - application/json
      parameters:
      - description: 删除用户信息
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/model.HandBook'
      produces:
      - application/json
      responses:
        "200":
          description: 单个用户信息的背包json数据
          schema:
            $ref: '#/definitions/model.MessageBind'
        "400":
          description: 400 bad request
          schema:
            $ref: '#/definitions/model.MessageBind'
      summary: 删除图鉴数据库的指定条目
      tags:
      - book-routers
  /handbookbyopenid:
    post:
      consumes:
      - application/json
      parameters:
      - description: 单个用户信息
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/model.HandBook'
      produces:
      - application/json
      responses:
        "200":
          description: 单个用户信息的背包json数据
          schema:
            $ref: '#/definitions/model.HandBook'
        "400":
          description: 400 bad request
          schema:
            $ref: '#/definitions/model.MessageBind'
      summary: 获取单个用户图鉴列表信息
      tags:
      - book-routers
  /inserthandbook:
    post:
      consumes:
      - application/json
      parameters:
      - description: 注册用户信息
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/model.HandBook'
      produces:
      - application/json
      responses:
        "200":
          description: 注册成功
          schema:
            $ref: '#/definitions/model.HandBook'
        "400":
          description: 注册失败
          schema:
            $ref: '#/definitions/model.MessageBind'
      summary: 注册新用户新建图鉴信息
      tags:
      - book-routers
  /insertrecruit:
    post:
      consumes:
      - application/json
      parameters:
      - description: 注册新招募板信息
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/routers.recruitJSON'
      produces:
      - application/json
      responses:
        "200":
          description: 注册成功
          schema:
            $ref: '#/definitions/model.MessageBind'
        "400":
          description: 注册失败
          schema:
            $ref: '#/definitions/model.MessageBind'
      summary: 注册新招募板信息
      tags:
      - recruit-routers
  /recruitbymakerid:
    post:
      consumes:
      - application/json
      parameters:
      - description: 单个用户信息
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/routers.recruitJSON'
      produces:
      - application/json
      responses:
        "200":
          description: 单个用户信息的背包json数据
          schema:
            $ref: '#/definitions/routers.recruitJSON'
        "400":
          description: 400 bad request
          schema:
            $ref: '#/definitions/model.MessageBind'
      summary: 获取单个用户图鉴列表信息
      tags:
      - recruit-routers
  /updatehandbook:
    post:
      consumes:
      - application/json
      parameters:
      - description: 更新用户信息
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/model.HandBook'
      produces:
      - application/json
      responses:
        "200":
          description: 单个用户信息的背包json数据
          schema:
            $ref: '#/definitions/model.MessageBind'
        "400":
          description: 400 bad request
          schema:
            $ref: '#/definitions/model.MessageBind'
      summary: 更新单个用户图鉴信息
      tags:
      - book-routers
swagger: "2.0"
