basePath: /api
definitions:
  model.HandBook:
    properties:
      monster1:
        type: integer
      monster2:
        type: integer
      monster3:
        type: integer
      monster4:
        type: integer
      monster5:
        type: integer
      monster6:
        type: integer
      monster7:
        type: integer
      openid:
        type: string
    type: object
  model.MessageBind:
    properties:
      message:
        type: string
    type: object
  model.UserData:
    properties:
      avatarurl:
        type: string
      experience:
        type: integer
      lifepoint:
        type: integer
      nickname:
        type: string
      openid:
        type: string
      soul:
        type: integer
      time:
        type: integer
    type: object
  model.UserPiece:
    properties:
      donghuangzhong:
        type: integer
      fuxiqin:
        type: integer
      haotianta:
        type: integer
      kongtongyin:
        type: integer
      kunlunjing:
        type: integer
      lianyaohu:
        type: integer
      nvwashi:
        type: integer
      openid:
        type: string
      pangufu:
        type: integer
      shennongding:
        type: integer
      xuanyuanjian:
        type: integer
    type: object
  routers.requests:
    properties:
      describe:
        type: string
      makerid:
        type: string
      openid:
        type: string
      time:
        type: integer
      title:
        type: string
    type: object
  routers.userCode:
    properties:
      code:
        type: string
      openid:
        type: string
      session_key:
        type: string
    type: object
host: 127.0.0.1:8848
info:
  contact:
    name: Doremy
    url: https://dimdoremy.github.io/
  description: 用于知夕番茄钟程序的后台api文档
  license: {}
  title: 知夕后台Api接口
  version: 1.0-golang
paths:
  /accept_recruit:
    post:
      consumes:
      - application/json
      parameters:
      - description: 招募请求
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/routers.requests'
      produces:
      - application/json
      responses:
        "200": {}
        "400":
          description: 错误信息
          schema:
            $ref: '#/definitions/model.MessageBind'
      summary: 接收客户端完成的积分
      tags:
      - recruit-routers
  /add_into_recruit:
    post:
      consumes:
      - application/json
      parameters:
      - description: 招募请求
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/routers.requests'
      produces:
      - application/json
      responses:
        "200": {}
        "400":
          description: 错误信息
          schema:
            $ref: '#/definitions/model.MessageBind'
      summary: 添加招募进入redis缓存
      tags:
      - recruit-routers
  /check_room:
    post:
      consumes:
      - application/json
      parameters:
      - description: 招募请求
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/routers.requests'
      produces:
      - application/json
      responses:
        "200": {}
        "400":
          description: 错误信息
          schema:
            $ref: '#/definitions/model.MessageBind'
      summary: 检查房间存在
      tags:
      - recruit-routers
  /complete_recruit:
    post:
      consumes:
      - application/json
      parameters:
      - description: 招募请求
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/routers.requests'
      produces:
      - application/json
      responses:
        "200": {}
        "400":
          description: 错误信息
          schema:
            $ref: '#/definitions/model.MessageBind'
      summary: 结算请求
      tags:
      - recruit-routers
  /delete_room:
    post:
      consumes:
      - application/json
      parameters:
      - description: 招募请求
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/routers.requests'
      produces:
      - application/json
      responses:
        "200": {}
        "400":
          description: 错误信息
          schema:
            $ref: '#/definitions/model.MessageBind'
      summary: 从redis缓存销毁招募房间
      tags:
      - recruit-routers
  /deletehandbook:
    post:
      consumes:
      - application/json
      parameters:
      - description: 删除用户信息
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/model.HandBook'
      produces:
      - application/json
      responses:
        "200":
          description: 删除成功
          schema:
            $ref: '#/definitions/model.MessageBind'
        "400":
          description: 400 bad request
          schema:
            $ref: '#/definitions/model.MessageBind'
      summary: 删除图鉴数据库的指定条目
      tags:
      - book-routers
  /deleteuserdata:
    post:
      consumes:
      - application/json
      parameters:
      - description: 更新的用户信息
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/model.UserData'
      produces:
      - application/json
      responses:
        "200":
          description: 删除成功
          schema:
            $ref: '#/definitions/model.MessageBind'
        "400":
          description: 400 bad request
          schema:
            $ref: '#/definitions/model.MessageBind'
      summary: 更新单个用户信息
      tags:
      - user-routers
  /deleteuserpiece:
    post:
      consumes:
      - application/json
      parameters:
      - description: 单个用户信息
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/model.UserPiece'
      produces:
      - application/json
      responses:
        "200":
          description: 删除成功
          schema:
            $ref: '#/definitions/model.MessageBind'
        "400":
          description: 删除失败
          schema:
            $ref: '#/definitions/model.MessageBind'
      summary: 删除背包数据库指定条目
      tags:
      - piece-routers
  /handbookbyopenid:
    post:
      consumes:
      - application/json
      parameters:
      - description: 单个用户信息
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/model.HandBook'
      produces:
      - application/json
      responses:
        "200":
          description: 单个用户图鉴信息的json数据
          schema:
            $ref: '#/definitions/model.HandBook'
        "400":
          description: 400 bad request
          schema:
            $ref: '#/definitions/model.MessageBind'
      summary: 获取单个用户图鉴列表信息
      tags:
      - book-routers
  /init_recruit:
    post:
      consumes:
      - application/json
      parameters:
      - description: 招募请求
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/routers.requests'
      produces:
      - application/json
      responses:
        "200": {}
        "400":
          description: 错误信息
          schema:
            $ref: '#/definitions/model.MessageBind'
      summary: 公共 活动 招募的读取
      tags:
      - recruit-routers
  /inserthandbook:
    post:
      consumes:
      - application/json
      parameters:
      - description: 注册用户信息
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/model.HandBook'
      produces:
      - application/json
      responses:
        "200":
          description: 注册成功
          schema:
            $ref: '#/definitions/model.MessageBind'
        "400":
          description: 注册失败
          schema:
            $ref: '#/definitions/model.MessageBind'
      summary: 注册新用户新建图鉴信息
      tags:
      - book-routers
  /insertuserdata:
    post:
      consumes:
      - application/json
      parameters:
      - description: 注册用户信息
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/model.UserData'
      produces:
      - application/json
      responses:
        "200":
          description: 注册成功
          schema:
            $ref: '#/definitions/model.MessageBind'
        "400":
          description: 注册失败
          schema:
            $ref: '#/definitions/model.MessageBind'
      summary: 注册单个用户
      tags:
      - user-routers
  /insertuserpiece:
    post:
      consumes:
      - application/json
      parameters:
      - description: 单个用户背包信息
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/model.UserPiece'
      produces:
      - application/json
      responses:
        "200":
          description: 注册成功
          schema:
            $ref: '#/definitions/model.MessageBind'
        "400":
          description: 注册失败
          schema:
            $ref: '#/definitions/model.MessageBind'
      summary: 注册单个用户，新建背包
      tags:
      - piece-routers
  /new_room:
    post:
      consumes:
      - application/json
      parameters:
      - description: 招募请求
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/routers.requests'
      produces:
      - application/json
      responses:
        "200": {}
        "400":
          description: 错误信息
          schema:
            $ref: '#/definitions/model.MessageBind'
      summary: 建立招募房间到redis缓存
      tags:
      - recruit-routers
  /openid:
    post:
      consumes:
      - application/json
      description: 用于服务器请求微信服务器进行用户登录授权使用
      parameters:
      - description: 用户的登录包
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/routers.userCode'
      produces:
      - application/json
      responses:
        "200":
          description: 请求结果
          schema:
            $ref: '#/definitions/routers.userCode'
        "400":
          description: 请求没到达
          schema:
            $ref: '#/definitions/model.MessageBind'
      summary: 请求微信登录授权
      tags:
      - wechat-router
  /piecebyopenid:
    post:
      consumes:
      - application/json
      parameters:
      - description: 单个用户信息
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/model.UserPiece'
      produces:
      - application/json
      responses:
        "200":
          description: 单个用户信息的json数据
          schema:
            $ref: '#/definitions/model.UserPiece'
      summary: 获取单个用户背包信息
      tags:
      - piece-routers
  /querybyopenid:
    post:
      consumes:
      - application/json
      parameters:
      - description: 单个用户信息
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/model.UserData'
      produces:
      - application/json
      responses:
        "200":
          description: 单个用户信息的json数据
          schema:
            $ref: '#/definitions/model.UserData'
        "400":
          description: 400 bad request
          schema:
            $ref: '#/definitions/model.MessageBind'
      summary: 获取单个用户信息
      tags:
      - user-routers
  /remove_recruit:
    post:
      consumes:
      - application/json
      parameters:
      - description: 招募请求
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/routers.requests'
      produces:
      - application/json
      responses:
        "200": {}
        "400":
          description: 错误信息
          schema:
            $ref: '#/definitions/model.MessageBind'
      summary: 从redis缓存退出招募
      tags:
      - recruit-routers
  /return_recruit:
    post:
      consumes:
      - application/json
      parameters:
      - description: 招募请求
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/routers.requests'
      produces:
      - application/json
      responses:
        "200": {}
        "400":
          description: 错误信息
          schema:
            $ref: '#/definitions/model.MessageBind'
      summary: 恢复客户端所有的redis缓存
      tags:
      - recruit-routers
  /updatehandbook:
    post:
      consumes:
      - application/json
      parameters:
      - description: 更新的用户信息
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/model.HandBook'
      produces:
      - application/json
      responses:
        "200":
          description: 更新成功
          schema:
            $ref: '#/definitions/model.MessageBind'
        "400":
          description: 400 bad request
          schema:
            $ref: '#/definitions/model.MessageBind'
      summary: 更新单个用户图鉴信息
      tags:
      - book-routers
  /updateuserdata:
    post:
      consumes:
      - application/json
      parameters:
      - description: 更新的用户信息
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/model.UserData'
      produces:
      - application/json
      responses:
        "200":
          description: 更新成功
          schema:
            $ref: '#/definitions/model.MessageBind'
        "400":
          description: 400 bad request
          schema:
            $ref: '#/definitions/model.MessageBind'
      summary: 更新单个用户信息
      tags:
      - user-routers
  /updateuserpiece:
    post:
      consumes:
      - application/json
      parameters:
      - description: 更新的用户背包信息
        in: body
        name: handBook
        required: true
        schema:
          $ref: '#/definitions/model.UserPiece'
      produces:
      - application/json
      responses:
        "200":
          description: 更新成功
          schema:
            $ref: '#/definitions/model.MessageBind'
        "400":
          description: 更新失败
          schema:
            $ref: '#/definitions/model.MessageBind'
      summary: 更新单个用户背包信息
      tags:
      - piece-routers
swagger: "2.0"
